config/routes.rb
Visitka::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' } ,:path=>'users/registrations'
  devise_for :users 
  devise_scope :user do
      get '/login'=> 'users/sessions#new', :as => :login
      post '/login'=> 'users/sessions#create'
      get '/signup'=> 'users/registrations#new', :as => :signup
      get  '/users/passwords'=> 'users/passwords#new'
      post  '/users/passwords'=> 'users/passwords#create'
      put  '/users/passwords'=> 'users/passwords#update'
      match '/account'=>'users#account'
      #get '/login' => 'devise/sessions#new', :as => :login
       get '/logout' => 'devise/sessions#destroy', :as => :logout
       get '/signup' => 'devise/registrations#new', :as => :signup
      get '/account/edit'=>'devise/registrations#edit'

  end
  resources :installments
  post  'installments/download' => 'installments#download_files_step'
  post  'installments/end'=> 'installments#instalations_end'
  resources :lic_keys, :only => [:create,:destroy]
  match 'lic_keys/generate'=>'lic_keys#update_key'
  match 'order_programm'=>'lic_requests#request_programm'
  resources :questionnaires
  resources :orders
  resources :line_items
  resources :lic_requests
   root :to => "home#index"
   match '/registrations_now'=>'home#register_now'
   resources :experts, :only=>[:show, :index]
   resources :feedbacks
   resources :materials, :only=>[:show, :index]
   get '/information_pages' =>'pages#index'
   get '/information_pages/:id'=>'pages#show', :as => :information_page 
   get 'information_pages/:page_id/children/:id'=>'children_pages#show'
    get '/programms'=>'materials#index'
    get '/programms/:id'=>'materials#show'
   resources :clients, :only=>[:show, :index]
   resources :programs_features
   get '/library/:id' =>'lib_books#show', :as => :lib_book
   resources :about, :only=>[:index]
   get '/news'=>'posts#index'
   get '/news/:id'=>'posts#show'
   resources :subscribers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
       root to: 'admin/admin_users#index'     
end

app/views/shared/_footer.html.slim
footer class="section-color-primarydark"
  div class="container"
    div class="row"
      div class='span1'
      div class="span3"
        div class="widget"
          address
            strong = @data_contacts.name
            br
            span = @data_contacts.address
            br
            abbr title="email" email:  
            span = mail_to @data_contacts.email
            br 
            abbr title="Телефон" Факс: 
            a 
              = @data_contacts.phone
      div class="span3"
        div class="widget"
          h5 Подписаться на новости
          p Следите за последними обновлениями
          span id='news-letter'
          = render :partial => 'subscribers/form', :locals => {:subscriber => Subscriber.new}
      div class="span3"
        div class="widget"
          h5 Свяжитесь с нами
          div class='contact-feed'
            = render :partial => 'feedbacks/form', :locals => {:feedback => Feedback.new}

app/views/shared/_header.html.slim
div class="container"
  div class="navbar"
    div class="navbar-inner"
      a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse"
        i class="icon-reorder"
      a class="brand span3" href="/"
        span style='font-size:224%; color:#fff;'
          strong="#{@data_contacts.name}"
      nav class="nav-collapse collapse "
        ul class="nav primary-nav pull-right menus"
          li class="active"id='home'
            a href="/" Главная
            li class="dropdown"id='programs_features'
              a class="dropdown-toggle" data-toggle="dropdown" href="#" 
                span Информация
                b class="caret"
              ul class="dropdown-menu"
                li id='about'
                  a href="/about"О компании
                li id='programs_features'
                  a href="/programs_features" Особенности программ
                li id='posts' 
                  = link_to 'Новости', '/news'
                  - @data_pages.each do |page|
                    li id='pages'
                      = link_to truncate(page.title, :lenght => 60), information_page_path(page)
              li id='materials'
                = link_to 'Программы','/programms'
              li class="dropdown" id='lib_books'
                a class="dropdown-toggle" data-toggle="dropdown" href="#"
                  span Библиотеки
                  b class="caret"
                ul class="dropdown-menu"
                  - @data_libs.each do |lib|
                    li
                      = link_to lib.title, lib_book_path(lib)
                li id='experts'
                  a href="/experts" Контакты     
              = render :partial => 'shared/login_bar'

app/views/shared/_login_bar.html.slim
- if current_user.nil?
 	li = link_to 'Вoйти', '/login'
- else
	li = link_to 'Личный кабинет', "/account" 
	li = link_to 'Выйти', '/logout'