config/routes.rb
Visitka::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' } ,:path=>'users/registrations'
  devise_for :users 
  devise_scope :user do
      get '/login'=> 'users/sessions#new', :as => :login
      post '/login'=> 'users/sessions#create'
      get '/signup'=> 'users/registrations#new', :as => :signup
      get  '/users/passwords'=> 'users/passwords#new'
      post  '/users/passwords'=> 'users/passwords#create'
      put  '/users/passwords'=> 'users/passwords#update'
      match '/account'=>'users#account'
      #get '/login' => 'devise/sessions#new', :as => :login
       get '/logout' => 'devise/sessions#destroy', :as => :logout
       get '/signup' => 'devise/registrations#new', :as => :signup
      get '/account/edit'=>'devise/registrations#edit'

  end
  resources :installments
  post  'installments/download' => 'installments#download_files_step'
  post  'installments/end'=> 'installments#instalations_end'
  resources :lic_keys, :only => [:create,:destroy]
  match 'lic_keys/generate'=>'lic_keys#update_key'
  match 'order_programm'=>'lic_requests#request_programm'
  resources :questionnaires
  resources :orders
  resources :line_items
  resources :lic_requests
   root :to => "home#index"
   match '/registrations_now'=>'home#register_now'
   resources :experts, :only=>[:show, :index]
   resources :feedbacks
   resources :materials, :only=>[:show, :index]
   get '/information_pages' =>'pages#index'
   get '/information_pages/:id'=>'pages#show', :as => :information_page 
   get 'information_pages/:page_id/children/:id'=>'children_pages#show'
    get '/programms'=>'materials#index'
    get '/programms/:id'=>'materials#show'
   resources :clients, :only=>[:show, :index]
   resources :programs_features
   get '/library/:id' =>'lib_books#show', :as => :lib_book
   resources :about, :only=>[:index]
   get '/news'=>'posts#index'
   get '/news/:id'=>'posts#show'
   resources :subscribers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
       root to: 'admin/admin_users#index'     
end

app/models/material.rb
class Material < ActiveRecord::Base
	attr_accessible :name, :installator_id, :price, :version, :installer_version,:price_description, :description,:preview,:features, :release, :created_at, :updated_at, :release,:releases_attributes
	validates_length_of :preview, :maximum=>200
	has_attached_file :release
	has_many :lic_keys
	belongs_to :installator
	#before_destroy :delete_releases
	#private
	#def delete_releases
	#	self.release.destroy
	#end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
	def index
		@materials_all = Material.all
		@materials = Kaminari.paginate_array(@materials_all).page(params[:page]).per(9)
		@clients = Client.first(6)
	end
	def show
		@material = Material.find(params[:id])
		
	end
end

app/views/materials/index.html.slim
section class="section-content section-services" id="section-services"
  div class="container"
    div class="row"
      div class="span3"
        h2 class="section-title"
          span Программы
          small Здесь представлены наши программные продукты
      div class="span9"
        div class="row"
          - @materials.each do |material|
            div class="span3"
              div class="text-center"
                figure
                  a href="/programms/#{material.id}"
                    i class="icon-cogs icon-8x icon-border"
                h4
                  = link_to material.name, "/programms/#{material.id}" 
                  p
                    = material.preview
/section
section class="section-content section-clients-on-carousel section-color-graylighter" id="section-clients-on-carousel"
  div class="container"
    div class="row"
      div class="span3"
        h2 class="section-title"
          span Клиенты
          small
      div class="span9"
        div class="row"
          div class="carousel carousel-mini slide" data-pause="true" id="myCarouselClients"
            div class="carousel-nav"
              div class="btn-group"
                a class="btn btn-link btn-small" data-slide="prev" href="#myCarouselClients"
                  i class="icon-chevron-left"
                a class="btn btn-link btn-small" data-slide="next" href="#myCarouselClients"
                  i class="icon-chevron-right"
            div class="carousel-inner"
              - unless @clients.empty?
                div class="item active"
                  - active_clients = @clients.shift(3)
                  - active_clients.each do |client|
                    - unless client.nil?
                      div class="span3"
                        figure class="hover-figcaption"
                          span
                            = image_tag client.photo.url(:medium)
                              div class="figcaption"
                                strong client.name
                div class="item"
                  - @clients.each do |client|
                    div class="span3"
                      figure class="hover-figcaption"
                        span 
                          = image_tag client.photo.url(:medium)
                            div class="figcaption"
                              strong client.name
= content_for :footer do 
  span

app/views/materials/show.html.slim
section class="section-content section-content-sidebar"
  div class="container"
    h2 class="section-title"
      = @material.name
    div class="row"
      div class="span8"
        article
          = raw @material.description
      div class="span3 offset1"
        aside
          div class="widget"
            h5 class="widget-title" Особенности программы
          div class="widget-content"
            p Здесь вы узнаете, почему именно эта  программа нужна вам
            span = link_to "Посмотреть","#{programs_features_path}#section-#{@material.id}"
= content_for :footer do 
  span